
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-08
owner: ucsb-cs156-f24
repo_name: team01-f24-08
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"aw-ucsborg-delete","number":72,"title":"aw - addes files for deleting UCSBorgs tables","url":"https://github.com/ucsb-cs156-f24/team01-f24-08/pull/72"},{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"aw-ucsborg-update","number":71,"title":"AW - added files for PUT methods, updating existing UCSBOrgs table","url":"https://github.com/ucsb-cs156-f24/team01-f24-08/pull/71"}]
