
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-08
owner: ucsb-cs156-f24
repo_name: team01-f24-08
pull_requests: [{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-MenuItemReviewDELETE","number":51,"title":"MenuItemReview table now has DELETE endpoint, 100% jacoco and pitest coverage","url":"https://github.com/ucsb-cs156-f24/team01-f24-08/pull/51"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-MenuItemReviewPUT","number":50,"title":"MenuItemReview PUT endpoint functional, 100% pitest and jacoco coverage","url":"https://github.com/ucsb-cs156-f24/team01-f24-08/pull/50"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-add-get-and-post","number":44,"title":"Cy articles add get and post","url":"https://github.com/ucsb-cs156-f24/team01-f24-08/pull/44"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-create-db","number":43,"title":"Cy articles create db","url":"https://github.com/ucsb-cs156-f24/team01-f24-08/pull/43"}]
